#--------------main configurations ---------
input_video_file_name: "pedestrian_human.mp4"
firebase_generated_json_file_name: "project_key.json"
count_send_interval_in_seconds: 60
draw: False  # No need to draw boxes
show_output: False
save_output: True
if_save_output_true_TimePeriod: 100

# -----YOLO model configurations ------------
yolo_confidence_score: 0.35
yolo_required_class_ids: [0]  # Class ID 0 corresponds to 'person' in YOLO models
yolo_input_img_size: 640

# ------- DeepSORT configurations -----------
max_cosine_dist: 0.2
nms_max_overlap: 1.0
max_iou_distance: 0.7
max_age: 70
n_init: 3
nn_budget: 100
use_cuda_for_deepsort: False
